package service

import "time"

const (
	HEARTBEAT_LIVENESS = 3
	HEARTBEAT_INTERVAL = 2500 * time.Millisecond
	HEARTBEAT_EXPIRY   = HEARTBEAT_INTERVAL * HEARTBEAT_LIVENESS
	PROTOCOL_CLIENT    = "RDC01"
	PROTOCOL_WORKER    = "RDW01"
	PROTOCOL_BROKER    = "RDB01"
)

const (
	_ = string(int(iota))
	COMMAND_READY
	COMMAND_REQUEST
	COMMAND_REPLY
	COMMAND_HEARTBEAT
	COMMAND_DISCONNECT
)
