package service

import "time"

const (
	HEARTBEAT_LIVENESS = 3
	HEARTBEAT_INTERVAL = 2500 * time.Millisecond
	HEARTBEAT_EXPIRY   = HEARTBEAT_INTERVAL * HEARTBEAT_LIVENESS
	PROTOCOL_CLIENT    = "MDPC02"
	PROTOCOL_WORKER    = "MDPW02"
)

const (
	_ = string(int(iota))
	COMMAND_READY
	COMMAND_REQUEST
	COMMAND_REPLY
	COMMAND_HEARTBEAT
	COMMAND_DISCONNECT
)
